### ISSUE TITLE
Publishing child apps from other authoring resources than dispatch app shows error

### ISSUE THREAD

**Issue by sibbl** [microsoft/botbuilder-tools#1424]
## Tool
Name: Dispatch
Version: 1.6.8
OS: Win 10 build 18363.720

## Describe the bug and reproduction steps

I have 2 LUIS child apps in different authoring resources. I want to create a dispatch app in authoring resource 1 (AR1), using an app from AR1 and using another app from AR2.

The script runs through and I can use the dispatch app afterwars. However I get the following error in the logs and am unsure whether it's any problem that the child apps are not republished (why are they published at all, I wonder?).

```
[...]
Publishing app1 model...
Publishing app2 model...
Failed adding subscription key/publishing app2 - {
  "error": {
    "code": "Unauthorized",
    "message": "The user is not the owner or a co-owner of this application."
  }
}
Training test-dispatch model...
Publishing test-dispatch model...
[...]
```

I guess it's internally using the key of AR1 instead of AR2 for this request?

## To Reproduce

Create a LUIS dispatch application using 
```
dispatch init -n "test-dispatch" --luisAuthoringKey "key1" --luisAuthoringRegion "westeurope"
dispatch add -t luis -i "id1" -k "key1" --intentName "app1"
dispatch add -t luis -i "id2" -k "key2" --intentName "app2"
dispatch create
```

## Expected behavior
No errors should be shown in the output.

[bug]

**Comment by tsuwandy** [comment]
@sibbl, are AR1/AR2 owned by the same user?  How about subscription key?  Trying to get a repro...

**Comment by sibbl** [comment]
@tsuwandy yes, both ARs were created by me. What could be specific is that the apps were all in AR2 beforehand. App1 created by me, app2 imported by a colleague. I then moved app1 into AR1 and created the dispatch app there.

**Comment by tsuwandy** [comment]
And Dispatch is created using AR1 (which also has prediction resource)?

**Comment by sibbl** [comment]
@tsuwandy yes, indeed. Dispatch and app1 are in AR2, app1 was kept in AR1.

**Comment by tsuwandy** [comment]
@sibbl I got a repro. Still investigating, will update this thread as soon I figure out how to fix.

**Comment by tsuwandy** [comment]
@sibbl , will have to consult with LUIS team what to do in this case.  

Is there specific reason they have to be in different apps?

**Comment by sibbl** [comment]
@tsuwandy you mean in different authoring resources? The background is mostly organizational so that we have a better separation of concern.

We have reusable Luis apps (AR2) and project specific Luis apps (AR1). Both kind of apps are combined into dispatch applications which we use for MS bot framework based chatbots for example.

**Comment by tsuwandy** [comment]
@sibbl, we just published an update to dispatch (version 1.6.9).    Ignore the child publishing error as long as the whole dispatch app is created, trained and published.    We still have to support both apps not yet migrated to Azure and also those already on Azure LUIS resource.   Let me know if you are seeing issues using the newly created Dispatch app.  Please reactivate this issue if you are not able to use the Dispatch app.   Thanks!

P.S. I tried querying the newly created dispatch and i was able to get the child result in the connectedServiceResult, see below.

{
  "query": "turn off light",
  "topScoringIntent": {
    "intent": "l_HomeAutomation",
    "score": 1.0
  },
  "intents": [
    {
      "intent": "l_HomeAutomation",
      "score": 1.0
    },
    {
      "intent": "None",
      "score": 6.6E-09
    },
    {
      "intent": "l_Weather",
      "score": 1.48148147E-10
    }
  ],
  "entities": [
    {
      "entity": "turn",
      "type": "Device_PatternAny",
      "startIndex": 0,
      "endIndex": 3,
      "role": ""
    }
  ],
  "connectedServiceResult": {
    "query": "turn off light",
    "topScoringIntent": {
      "intent": "ControlDevice",
      "score": 1.0
    },
    "intents": [
      {
        "intent": "ControlDevice",
        "score": 1.0
      },
      {
        "intent": "None",
        "score": 3.9E-09
      }
    ],
    "entities": [
      {
        "entity": "light",
        "type": "Device",
        "startIndex": 9,
        "endIndex": 13,
        "score": 0.9847512
      },
      {
        "entity": "turn off",
        "type": "Operation",
        "startIndex": 0,
        "endIndex": 7,
        "resolution": {
          "values": [
            "off"
          ]
        }
      },
      {
        "entity": "off",
        "type": "Operation",
        "startIndex": 5,
        "endIndex": 7,
        "resolution": {
          "values": [
            "off"
          ]
        }
      },
      {
        "entity": "turn",
        "type": "Device_PatternAny",
        "startIndex": 0,
        "endIndex": 3,
        "role": ""
      }
    ]
  }
}

**Comment by sibbl** [comment]
> Let me know if you are seeing issues using the newly created Dispatch app.

The error above is still happening with 1.6.9

> Please reactivate this issue if you are not able to use the Dispatch app. 

Tricky question as I can obviously use the Dispatch app.

So as far as I understand this issue should be closed, although it's not fixed (even though it's just a UI thing) but I can safely ignore the error for now and should not report any issue again? Well, okay then. 🤷‍♂️

**Comment by tsuwandy** [comment]
@sibbl , the child publishing error could be safely ignored as long as the dispatch app is created, trained and published.  Make sure you could use it at run time and that you could get back the child result as well.  create command failed for me before v 1.6.9.

The tool still needs to support LUIS apps that have not yet been converted to use Azure LUIS resource, unfortunately there is no way for the tool to know whether LUIS app is using Azure resource or the old authoring model.

Let me know if you are not able to use the Dispatch app at run time.
