### ISSUE TITLE
LuisGen .cs output using outdated package names

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#390]
The generated LuisGen .cs file references the Microsoft.Bot.Builder.Ai.LUIS package, but this package name has been updated to  Microsoft.Bot.Builder.AI.Luis, which causes errors from the start. 

Also, Microsoft.Bot.Builder.Core.Extensions.IRecognizerConvert is now Microsoft.Bot.Builder.IRecognizerConvert.

**Comment by vishwacsena** [comment]
@chrimc62 - is this addressed in your un-merged luisgen branch? If not, we should make sure that this is addressed.

**Comment by chrimc62** [comment]
Yes, the rename broke LUISGen.  I will fix it.

**Comment by chrimc62** [comment]
Fixed and checked in.  Binaries are in \\chrimc2\public\luisgen until official package release.

**Comment by mekinney** [comment]
Is this official packaged released yet?  It's still broken in 2.0.2.0...
