### ISSUE TITLE
appId with value "[object Object]" must be of type string and a valid uuid.

### ISSUE THREAD

**Issue by damadei** [Microsoft/botbuilder-tools#937]
## Tool
Name: LUIS
Version: 2.2.0
OS: Windows 10

## Describe the bug
When I run luis add application --in password.luis i get the following error:

appId with value "[object Object]" must be of type string and a valid uuid.

## To Reproduce
1. Just run the command above

**Comment by sramayanam** [comment]
I am still getting the error. Does this change go live yet? if so what are the steps

**Comment by vishnu2017** [comment]
Same issue. Looking for resolution

**Comment by jbinard** [comment]
This error is a real issue when trying to automate the luis app creation. Can you release a new version of luis-apis tool considering that the fix was merged to master a month ago ?

**Comment by KinleyP** [comment]
Problem still exists. The tool seems generally not to work very well. Importing an app or a version is simply impossible.

**Comment by a-hohaze** [comment]
@KinleyP I was able to import a JSON app by that command. I am currently using package version 2.6.2.

I have a couple of questions.

Is the app in JSON format or LU format?

are you on the latest version?

Can you share a sample app JSON that you are failing to import to be able to reproduce?

**Comment by KinleyP** [comment]
Hi,

The app is in JSON format and I am using version 2.6.2
I exported the JSON file from the LUIS (preview) portal and did not touch the file (no contamination from my side)

I am using this command:
luis import application --in ".\<FILENAME>.json" --authoringKey "<MYAUTHORINGKEY>" --endpoint "https://<MYCUSTOMERDEMONAME>-authoring.cognitiveservices.azure.com/" --name "<NEWAPPNAME>"

And I am always getting this error message:
luisApp.entities.children with value "[object Object]" must be of type string.

Is there something like a minimal JSON / LU file, that can be used for a basic import test? I think you cannot use LU files directly with the LUIS CLI, only JSON.
I tried to convert LU files with the BF CLI tool, but that seems to leave out some mandatory sections in the JSON file (e.g. Phraselists) - so these files will not import at all. - But I guess the BF CLI tool is a different topic.

I am a bit reluctant to share a JSON or LU file, as I want to make sure, that the customer name does not get revealed...

Many thanks
regards
Edzard

**Comment by a-hohaze** [comment]
Issue resolved for @KinleyP . 
Edzard was getting a different error on import which is "BadArgument: Missing phraselist features field. "
It seems Edzard was exporting the app using the preview portal which uses V3-Preview authoring APIs while the current LUIS tool uses V2 APIs so the import operation was failing due to incompatibility of the API versions.
